FROM python:3.9-slim

RUN rm /etc/apt/sources.list.d/cuda.list

RUN apt-get update
RUN apt-get install -y unzip graphviz gcc
RUN apt-get update
RUN apt-get install -y musescore3

RUN pip install --upgrade pip

WORKDIR /app

COPY ./requirements.txt /app
RUN pip install -r /app/requirements.txt

COPY /utils/. /app/utils
COPY /notebooks/. /app/notebooks
COPY /scripts/. /app/scripts

COPY /setup.cfg /app

ENV PYTHONPATH="${PYTHONPATH}:/app"